import { Book, Page, Word, QRCodeRecord } from '../types';

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'b1-tai-khamyang',
    title: 'Tai Khamyang Speaking Book',
    description: 'Essential conversational phrases, sacred vocabulary, daily dialogue, and phonetic pronunciation guide for Tai Khamyang language revitalization in Assam.',
    author: 'Tai Language Society & Heritage Council',
    language: 'Tai Khamyang',
    cover_image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    created_at: new Date('2025-01-10T10:00:00Z').toISOString(),
    updated_at: new Date('2025-01-10T10:00:00Z').toISOString(),
  },
  {
    id: 'b2-tai-phake',
    title: 'Tai Phake Conversational Primer',
    description: 'Folk proverbs, village life expressions, flora and fauna terminology, and grammatical structures preserved by Tai Phake communities in Namphake village.',
    author: 'Phake Cultural Preservation Mission',
    language: 'Tai Phake',
    cover_image_url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    created_at: new Date('2025-02-01T10:00:00Z').toISOString(),
    updated_at: new Date('2025-02-01T10:00:00Z').toISOString(),
  }
];

export const INITIAL_PAGES: Page[] = [
  {
    id: 'p1-khamyang-p25',
    book_id: 'b1-tai-khamyang',
    page_number: 25,
    page_title: 'Daily Greetings and Respectful Salutations',
    page_image_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1000&q=80',
    page_text: `မႂ်ႇသုင်ၶႃႈ (Mai-sung kha)

In Tai Khamyang tradition, respectful greeting begins when entering a village or elder's residence. The speaker gently bows the head with palms joined at the chest (Wai) and utters "Mai-sung kha" to invite auspicious blessings.

Elder replies: "Yu di kin wan" (May you live well and eat sweet food).
This lesson introduces fundamental conversational tokens used every morning in Tai villages across Margherita and Disangpani. Always remember to maintain an affectionate and humble vocal inflection.`,
    full_page_audio_url: 'https://actions.google.com/sounds/v1/water/rain_heavy.ogg', // Sample test audio file
    summary: 'Page 25 covers the primary greeting rituals, respectful tones used when addressing community elders, and the cultural philosophy of wishing health and sweet sustenance to guests.',
    summary_audio_url: 'https://actions.google.com/sounds/v1/water/rain_heavy.ogg',
    qr_token: 'ABC123XYZ',
    created_at: new Date('2025-01-10T11:00:00Z').toISOString(),
    updated_at: new Date('2025-01-10T11:00:00Z').toISOString(),
  },
  {
    id: 'p2-khamyang-p26',
    book_id: 'b1-tai-khamyang',
    page_number: 26,
    page_title: 'Family Relationships and Kinship Terms',
    page_image_url: 'https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?auto=format&fit=crop&w=1000&q=80',
    page_text: `Kinship titles in Tai Khamyang reflect hierarchy, respect, and warm familial bonds. Elders are addressed with sacred prefixes honoring their lineage and generational guidance.

When speaking of parents, "Pho" represents father and "Mae" represents mother. Younger siblings look up to "Pi", while older siblings protect "Nong".`,
    full_page_audio_url: '',
    summary: 'Page 26 introduces kinship vocabulary such as Mother (Mae), Father (Pho), Elder Brother (Pi Chai), and Younger Sister (Nong Sao).',
    summary_audio_url: '',
    qr_token: 'XYZ789PQR',
    created_at: new Date('2025-01-10T12:00:00Z').toISOString(),
    updated_at: new Date('2025-01-10T12:00:00Z').toISOString(),
  },
  {
    id: 'p3-phake-p10',
    book_id: 'b2-tai-phake',
    page_number: 10,
    page_title: 'Rice Cultivation and River Ecosystem',
    page_image_url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=80',
    page_text: `Tai Phake settlements thrive along the Burhi Dihing river. Rice ("Khao") is both sacred nourishment and the focal point of community celebration. During sowing season, songs of encouragement echo through the misty fields.`,
    full_page_audio_url: '',
    summary: 'Page 10 explores agricultural rituals, rice harvesting vocabulary, and river ecology terms central to Phake identity.',
    summary_audio_url: '',
    qr_token: 'PHAKE010',
    created_at: new Date('2025-02-01T11:00:00Z').toISOString(),
    updated_at: new Date('2025-02-01T11:00:00Z').toISOString(),
  }
];

export const INITIAL_WORDS: Word[] = [
  {
    id: 'w1',
    page_id: 'p1-khamyang-p25',
    word: 'မႂ်ႇသုင်ၶႃႈ',
    phonetic: 'Mai-sung kha',
    meaning: 'Traditional Tai greeting wishing growth, prosperity, and sacred peace.',
    assamese_meaning: 'নমস্কাৰ / মঙ্গল হওক (সন্মানীয় সম্ভাষণ)',
    english_meaning: 'Hello / Greetings / Auspicious blessing',
    example_sentence: 'မႂ်ႇသုင်ၶႃႈ ပေႃႈထဝ်ႈ (Mai-sung kha pho thao)',
    example_assamese: 'নমস্কাৰ ককা (সন্মানীয় বৃদ্ধক সম্ভাষণ)',
    example_english: 'Greetings respected elder grandfather.',
    word_audio_url: 'https://actions.google.com/sounds/v1/water/rain_heavy.ogg',
    meaning_audio_url: '',
    example_audio_url: '',
    display_order: 1,
    created_at: new Date('2025-01-10T11:10:00Z').toISOString(),
    updated_at: new Date('2025-01-10T11:10:00Z').toISOString(),
  },
  {
    id: 'w2',
    page_id: 'p1-khamyang-p25',
    word: 'ယူႇလီ',
    phonetic: 'Yu di',
    meaning: 'State of being healthy, tranquil, and sound in body and mind.',
    assamese_meaning: 'ভালে থকা / কুশলে থকা / সুস্বাস্থ্য',
    english_meaning: 'To be well / healthy / peaceful',
    example_sentence: 'သူၵေႃႉ ယူႇလီယူႇႁႃႉ? (Su kau yu di yu ha?)',
    example_assamese: 'আপুনি ভালে আছেনে?',
    example_english: 'Are you doing well and healthy?',
    word_audio_url: 'https://actions.google.com/sounds/v1/water/rain_heavy.ogg',
    meaning_audio_url: '',
    example_audio_url: '',
    display_order: 2,
    created_at: new Date('2025-01-10T11:15:00Z').toISOString(),
    updated_at: new Date('2025-01-10T11:15:00Z').toISOString(),
  },
  {
    id: 'w3',
    page_id: 'p1-khamyang-p25',
    word: 'ၵိၼ်ဝၢၼ်',
    phonetic: 'Kin wan',
    meaning: 'Literally "eat sweet/delicious", expressing blessing for contentment and abundance.',
    assamese_meaning: 'সুস্বাদু ভোজন / তৃপ্তিৰে খোৱা',
    english_meaning: 'To eat deliciously / have an enjoyable meal',
    example_sentence: 'ႁဝ်းမႃး ၵိၼ်ၶဝ်ႈဝၢၼ် (Hao ma kin khao wan)',
    example_assamese: 'আহক আমি আনন্দৰে ভাত খাওঁ',
    example_english: 'Come let us enjoy a sweet wholesome meal together.',
    word_audio_url: '',
    meaning_audio_url: '',
    example_audio_url: '',
    display_order: 3,
    created_at: new Date('2025-01-10T11:20:00Z').toISOString(),
    updated_at: new Date('2025-01-10T11:20:00Z').toISOString(),
  },
  {
    id: 'w4',
    page_id: 'p1-khamyang-p25',
    word: 'ယိၼ်းၸူမ်းၶႃႈ',
    phonetic: 'Yin sum kha',
    meaning: 'Expressing deep heartfelt gratitude and humble appreciation.',
    assamese_meaning: 'ধন্যবাদ / আন্তৰিক কৃতজ্ঞতা',
    english_meaning: 'Thank you very much / grateful appreciation',
    example_sentence: 'ယိၼ်းၸူမ်းၶႃႈ တၢင်းၸွႆႈထႅမ် (Yin sum kha tang soi them)',
    example_assamese: 'আপোনাৰ সহায়ৰ বাবে বহুত ধন্যবাদ',
    example_english: 'Thank you deeply for your kind assistance.',
    word_audio_url: '',
    meaning_audio_url: '',
    example_audio_url: '',
    display_order: 4,
    created_at: new Date('2025-01-10T11:25:00Z').toISOString(),
    updated_at: new Date('2025-01-10T11:25:00Z').toISOString(),
  },
  // Page 26 words
  {
    id: 'w5',
    page_id: 'p2-khamyang-p26',
    word: 'ပေႃႈ',
    phonetic: 'Pho',
    meaning: 'Father / Patriarch of the family household.',
    assamese_meaning: 'পিতা / দেউতা',
    english_meaning: 'Father',
    example_sentence: 'ပေႃႈ ၵႂႃႇၼႃး (Pho kwa na)',
    example_assamese: 'দেউতা পথাৰলৈ গৈছে',
    example_english: 'Father goes to the paddy field.',
    word_audio_url: '',
    meaning_audio_url: '',
    example_audio_url: '',
    display_order: 1,
    created_at: new Date('2025-01-10T12:10:00Z').toISOString(),
    updated_at: new Date('2025-01-10T12:10:00Z').toISOString(),
  },
  {
    id: 'w6',
    page_id: 'p2-khamyang-p26',
    word: 'မႄႈ',
    phonetic: 'Mae',
    meaning: 'Mother / Matriarch caring for the household.',
    assamese_meaning: 'মাতৃ / মা',
    english_meaning: 'Mother',
    example_sentence: 'မႄႈ ႁဵတ်းၽၵ်း (Mae het phak)',
    example_assamese: 'মা-ই ব্যঞ্জন ৰান্ধিছে',
    example_english: 'Mother prepares food.',
    word_audio_url: '',
    meaning_audio_url: '',
    example_audio_url: '',
    display_order: 2,
    created_at: new Date('2025-01-10T12:15:00Z').toISOString(),
    updated_at: new Date('2025-01-10T12:15:00Z').toISOString(),
  }
];

export const INITIAL_QR_CODES: QRCodeRecord[] = [
  {
    id: 'qr1',
    page_id: 'p1-khamyang-p25',
    token: 'ABC123XYZ',
    qr_url: `${window.location.origin}/learn/ABC123XYZ`,
    scan_count: 42,
    created_at: new Date('2025-01-10T11:00:00Z').toISOString(),
  },
  {
    id: 'qr2',
    page_id: 'p2-khamyang-p26',
    token: 'XYZ789PQR',
    qr_url: `${window.location.origin}/learn/XYZ789PQR`,
    scan_count: 18,
    created_at: new Date('2025-01-10T12:00:00Z').toISOString(),
  },
  {
    id: 'qr3',
    page_id: 'p3-phake-p10',
    token: 'PHAKE010',
    qr_url: `${window.location.origin}/learn/PHAKE010`,
    scan_count: 9,
    created_at: new Date('2025-02-01T11:00:00Z').toISOString(),
  }
];
